### ISSUE TITLE
Mixin for ::selection

### ISSUE THREAD

**Issue by rands0n** [randsonjs/stretch#5]
I was thinking of abstracting the `::selection`. Leaves everything in a mixin.

This mixin works perfectly:

``` css
.selection(@background-color: #f16529, @color: #FFF) {
    &::-moz-selection {
        background-color: @background-color;
        color: @color;
        text-shadow: none;
    }
    &::selection {
        background-color: @background-color;
        color: @color;
        text-shadow: none;
    }
}
```
#### Usage:

``` css
.selection(#333, #FFF);
```
#### Output:

``` css
::-moz-selection {
  background-color: #333333;
  color: #ffffff;
  text-shadow: none;
}
::selection {
  background-color: #333333;
  color: #ffffff;
  text-shadow: none;
}
```
